baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Dan Repacholi presentation by Ian Scrivener'
theme = ["reveal-hugo"]


[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true


